// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUz0-p_YBZYRah2cW0A_edE2Aqlb5vIhA',
    appId: '1:53378654144:web:86682905ff41ba8af97225',
    messagingSenderId: '53378654144',
    projectId: 'finmaker-9cbd4',
    authDomain: 'finmaker-9cbd4.firebaseapp.com',
    storageBucket: 'finmaker-9cbd4.appspot.com',
    measurementId: 'G-XXT3PL7FQZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5TPPCNKDc0MKDbAMua-vhjM5_fAw7ujU',
    appId: '1:53378654144:android:e54c5f7b31788155f97225',
    messagingSenderId: '53378654144',
    projectId: 'finmaker-9cbd4',
    storageBucket: 'finmaker-9cbd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrTeccIaRuh2DjiBzJKZCQKMiM_BMHkaI',
    appId: '1:53378654144:ios:b3a18aca7cfb8c46f97225',
    messagingSenderId: '53378654144',
    projectId: 'finmaker-9cbd4',
    storageBucket: 'finmaker-9cbd4.appspot.com',
    iosBundleId: 'com.example.finmaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrTeccIaRuh2DjiBzJKZCQKMiM_BMHkaI',
    appId: '1:53378654144:ios:b3a18aca7cfb8c46f97225',
    messagingSenderId: '53378654144',
    projectId: 'finmaker-9cbd4',
    storageBucket: 'finmaker-9cbd4.appspot.com',
    iosBundleId: 'com.example.finmaker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUz0-p_YBZYRah2cW0A_edE2Aqlb5vIhA',
    appId: '1:53378654144:web:d65aa51ff06c7181f97225',
    messagingSenderId: '53378654144',
    projectId: 'finmaker-9cbd4',
    authDomain: 'finmaker-9cbd4.firebaseapp.com',
    storageBucket: 'finmaker-9cbd4.appspot.com',
    measurementId: 'G-9W4CKH0EDT',
  );
}
